[data]
    email = "your.email@example.com"
    name = "Your Name"

[data.core]
    editor = "nvim"

[data.paths]
    # Add additional paths if needed for different machines
    # These will be available as variables in your templates
    homebrew = "/opt/homebrew"
    
[data.conda]
    # Toggle conda integration based on machine
    enabled = true
    path = "~/miniconda3" 